#!/bin/sh

. /config.sh

export PATH=/bin
mount proc /proc -t proc
mount sys /sys -t sysfs
mount devtmpfs /dev -t devtmpfs
mount debugfs /sys/kernel/debug -t debugfs
mount tracefs /sys/kernel/debug/tracing -t tracefs
mkdir /dev/pts
mount devpts /dev/pts -t devpts
ln -s /bin /usr/bin
ln -s /proc/self/fd /dev/fd
ip link set eth0 up
ip link set eth0 up
ip route add 0.0.0.0/0 via 192.168.222.1
udhcp -i eth0
mkdir /host
mount -t 9p -o trans=virtio host /host -oversion=9p2000.L,msize=16777216
telnetd -p $HOST_TELNET_PORT
